title: gmpxxll
authors:
  - "<a href='https://github.com/flatsurf/gmpxxll/blob/master/AUTHORS'>the gmpxxll contributors</a>"
description: >-
  a header-only to bring long long to GMP's C++ interface.
baseurl: "/"
url: ""
github_username: flatsurf
github_blob: "https://github.com/flatsurf/gmpxxll/blob/master/"

header_pages:
  - None

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-optional-front-matter

