channel_targets:
  - flatsurf main
channel_sources:
  - flatsurf,conda-forge,defaults
target:
  - release
  - style
  - test
  - coverage
  - benchmark
name:
  - gmpxxll
  - gmpxxll
  - gmpxxll
  - gmpxxll
  - gmpxxll
zip_keys:
  - target
  - name
