{% set version = '1.0.0' %}
{% set build_number = '0' %}

package:
  name: gmpxxll
  version: {{ version }}

source:
  path: ../

build:
  number: {{ build_number }}
  # conda's default C++ compiler is not C++17 ready yet
  skip: True  [win or osx]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - gmp

about:
  home: https://github.com/flatsurf/gmpxxll
  license: MIT
  license_file: COPYING
  summary: A header only library that adds some long long functions for GMP's C++ interface.
