ignore:
  - "^.*.benchmark.cc$"
  - "^.*/benchmark/.*$"
  - "^benchmark/.*$"
  - "**/*.benchmark.cc"
  - "**/benchmark/*"
  - "benchmark/*"
  - "^.*.test.cc$"
  - "^.*/test/.*$"
  - "^test/.*$"
  - "**/*.test.cc"
  - "**/test/*"
  - "test/*"
