# This file lists the dependencies needed to build the documentation of
# gmpxxll.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -n doc-gmpxxll-build -f environment.yml
# conda env update -n doc-gmpxxll-build -f doc/environment.yml
name: doc-eantic-build
channels:
  - conda-forge
dependencies:
  - saraedum::standardese>=0.6.0
  - mkdocs>=1.1.0
  - linkchecker
