name: Code Coverage
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive, fetch-depth: 0 }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: make check
        shell: bash -l {0}
        run: |
          ./bootstrap
          export CXXFLAGS="$CXXFLAGS --coverage -O0 -UNDEBUG"
          ./configure --prefix="$PREFIX" --without-benchmark --without-doc
          make check
      - name: create & post coverage report
        shell: bash -l {0}
        run: |
          pushd test
          gcov -pbs ../../gmpxxll mpz_class.test.gcda
          popd
          curl -s https://codecov.io/bash | bash -s - -X gcov -R `pwd` .
      - name: show logs
        run: grep "" /dev/null `find -name '*.log'` || true
        if: ${{ always() }}

env:
  MAKEFLAGS: -j2
