name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.on }}
    strategy:
      matrix:
        include:
        - { task: "test", on: "ubuntu-24.04" }
        - { task: "test", on: "macos-13" }
        - { task: "test-valgrind", on: "ubuntu-24.04" }
        - { task: "distcheck", on: "ubuntu-24.04" }
        - { task: "distcheck", on: "macos-13" }
    steps:
      - uses: actions/checkout@v5
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.9.2
        with: { pixi-version: v0.42.1 }
      - name: install valgrind dependencies
        run: |
          sudo apt update
          sudo apt install -y libc6-dbg
        if: endsWith(matrix.task || '', 'valgrind')
      - name: run ${{ matrix.task }}
        run: pixi run ${{ matrix.task }}
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}
